name: commit checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Dependencies
        run: NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn

      - name: Run tests
        run: NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn test

      - name: Coverage reports
        uses: actions/upload-artifact@v2.2.4
        with:
          name: coverage 
          path: test-report.xml

      - name: SonarCloud
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 